[package]
name = "alakkazam"
version = "0.1.0"
authors = ["Daniel David Sansano Surla <s3729065@student.rmit.edu.au>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
